# Generated by Django 3.0 on 2022-02-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description_short', models.TextField(blank=True, default='', verbose_name='Краткое описание')),
                ('description_long', models.TextField(blank=True, default='', verbose_name='Полное описание')),
                ('lat', models.FloatField(default=55, verbose_name='Широта')),
                ('lon', models.FloatField(default=37, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Экскурсия',
                'verbose_name_plural': 'Экскурсии',
            },
        ),
    ]
