# Generated by Django 3.0 on 2022-02-14 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo', verbose_name='Файл изображения')),
                ('sort_index', models.SmallIntegerField(default=1, verbose_name='Порядок вывода')),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exc_photos', to='places.Excursion', verbose_name='Экскурсия')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
