# Generated by Django 3.0 on 2022-02-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['sort_index'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterField(
            model_name='image',
            name='sort_index',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок вывода'),
        ),
    ]
