# Generated by Django 3.0 on 2022-02-24 12:30

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20220221_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='description_long',
            field=tinymce.models.HTMLField(blank=True, default='There is no description_long', verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='description_short',
            field=models.TextField(blank=True, default='There is no description_short', verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='title',
            field=models.CharField(default='There is no title', max_length=100, verbose_name='Название'),
        ),
    ]
